"""
Offer Document model — output of the Closer agent.

Generates persuasive, legally-safe commercial strategy drafts for property offers.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class SellerMotivation(str, Enum):
    """Detected or inferred seller motivation level."""
    DESPERATE = "desperate"         # Mortgagee, divorce, deceased estate
    MOTIVATED = "motivated"         # Must sell, relocating, downsizing
    NEUTRAL = "neutral"             # Normal market sale
    ASPIRATIONAL = "aspirational"   # Testing the market at a high price
    UNKNOWN = "unknown"


class OfferTone(str, Enum):
    """Tone of the offer letter."""
    EMPATHETIC = "empathetic"
    PROFESSIONAL = "professional"
    URGENT = "urgent"
    FAMILY_STORY = "family_story"
    INVESTOR_DIRECT = "investor_direct"


class OfferCondition(BaseModel):
    """A condition/clause in the offer."""
    name: str = Field(..., description="Condition name e.g. 'Building & Pest Inspection'")
    description: str = Field(..., description="Full condition text")
    days: Optional[int] = Field(None, description="Days allowed for this condition")
    is_waivable: bool = Field(default=True, description="Can this condition be waived?")


class OfferDocument(BaseModel):
    """
    A complete offer strategy document generated by the Closer agent.

    LEGAL DISCLAIMER: This is a Commercial Strategy Draft, not legal advice.
    Users should engage a licensed conveyancer or solicitor before signing.
    """

    id: UUID = Field(default_factory=uuid4)
    created_at: datetime = Field(default_factory=datetime.utcnow)

    # --- Property Reference ---
    property_id: UUID
    property_address: str

    # --- Buyer ---
    buyer_name: str
    buyer_entity: Optional[str] = Field(None, description="Company/trust name if applicable")

    # --- Offer Details ---
    offer_price: float = Field(..., ge=0, description="Offer amount AUD")
    deposit_amount: float = Field(..., ge=0, description="Deposit AUD (usually 5-10%)")
    settlement_days: int = Field(default=42, ge=14, le=180, description="Settlement period in days")
    finance_approval_days: int = Field(default=21, ge=0, le=90)

    # --- Strategy ---
    seller_motivation: SellerMotivation = SellerMotivation.UNKNOWN
    offer_tone: OfferTone = OfferTone.PROFESSIONAL
    conditions: list[OfferCondition] = Field(default_factory=list)

    # --- Generated Content ---
    cover_letter: str = Field(
        default="",
        description="The persuasive cover/offer letter"
    )
    negotiation_talking_points: list[str] = Field(
        default_factory=list,
        description="Key talking points for phone negotiation"
    )
    counter_offer_strategy: str = Field(
        default="",
        description="Strategy if the seller counters"
    )
    walk_away_price: Optional[float] = Field(
        None, ge=0,
        description="Maximum price — walk away above this"
    )

    # --- Legal Safety ---
    legal_disclaimer: str = Field(
        default=(
            "COMMERCIAL STRATEGY DRAFT — NOT LEGAL ADVICE. "
            "This document is generated by NexusProp AI as a commercial strategy tool. "
            "It does not constitute legal advice, a binding contract, or a formal offer. "
            "Buyers must engage a licensed Australian conveyancer or solicitor to review "
            "and formalise any offer before submission. NexusProp Pty Ltd accepts no "
            "liability for decisions made based on this document."
        ),
        description="Mandatory legal disclaimer"
    )

    @property
    def deposit_pct(self) -> float:
        if self.offer_price == 0:
            return 0
        return round((self.deposit_amount / self.offer_price) * 100, 1)

    @property
    def discount_from_asking(self) -> Optional[float]:
        """Calculated externally — placeholder for serialisation."""
        return None

    def get_standard_conditions(self) -> list[OfferCondition]:
        """Return standard Australian offer conditions."""
        return [
            OfferCondition(
                name="Finance Approval",
                description=(
                    "This offer is subject to the Buyer obtaining unconditional "
                    "finance approval from an authorised deposit-taking institution "
                    "within the specified period."
                ),
                days=self.finance_approval_days,
                is_waivable=True,
            ),
            OfferCondition(
                name="Building & Pest Inspection",
                description=(
                    "This offer is subject to a satisfactory building and pest "
                    "inspection report being obtained at the Buyer's expense."
                ),
                days=14,
                is_waivable=True,
            ),
            OfferCondition(
                name="Strata Report (if applicable)",
                description=(
                    "This offer is subject to review and satisfaction with the "
                    "Strata Inspection Report including all by-laws, minutes of "
                    "meetings, sinking fund details, and any special levies."
                ),
                days=14,
                is_waivable=True,
            ),
            OfferCondition(
                name="Section 32 / Contract Review",
                description=(
                    "This offer is subject to the Buyer's solicitor or conveyancer "
                    "reviewing and approving the Contract of Sale / Section 32 "
                    "Vendor's Statement."
                ),
                days=7,
                is_waivable=False,
            ),
        ]


class OfferGenerationRequest(BaseModel):
    """Input request to generate an offer document."""

    property_id: UUID
    property_address: str
    asking_price: float = Field(..., ge=0)
    buyer_name: str
    buyer_entity: Optional[str] = None
    buyer_budget_max: float = Field(..., ge=0)
    buyer_story: Optional[str] = Field(
        None,
        description="Personal story for empathetic offers (e.g., 'First home for our family')"
    )
    seller_motivation: SellerMotivation = SellerMotivation.UNKNOWN
    preferred_tone: OfferTone = OfferTone.PROFESSIONAL
    include_conditions: bool = True
    offer_price_override: Optional[float] = Field(
        None, ge=0,
        description="If set, use this price instead of calculated optimal"
    )
    settlement_days: int = Field(default=42, ge=14, le=180)
    additional_context: Optional[str] = None
